# Generated by Django 5.1.6 on 2025-02-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('plan_detail', models.TextField()),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=500, null=True)),
                ('speaker_image', models.ImageField(upload_to='speakers/')),
                ('speaker_name', models.CharField(max_length=100)),
                ('speaker_position', models.CharField(max_length=100)),
                ('speaker_description', models.TextField()),
                ('speaker_Linkedin_account', models.URLField(blank=True, null=True)),
                ('speaker_Twitter_account', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
